version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  # real-time-location:
  #   image: rafa93br/real-time-location
  #   build: .
  #   deploy:
  #     replicas: 3
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - redis
  #   volumes:
  #     - "./:/usr/src/app"
  #   links:
  #     - redis
  #   entrypoint: "yarn run start"